# Generated by Django 3.2.7 on 2021-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
