# Generated by Django 3.2.7 on 2021-10-10 16:22

import adminlte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0008_auto_20211009_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='images/default-150x150.png', null=True, upload_to=adminlte.models.filepath),
        ),
    ]
