# Generated by Django 3.2.7 on 2021-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
