# Generated by Django 3.2.7 on 2021-10-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0013_alter_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Out Of Stock')], default=0),
        ),
    ]
