# Generated by Django 3.2.7 on 2021-10-10 23:49

import adminlte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0014_auto_20211010_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adminlte.models.filepath),
        ),
    ]
