# Generated by Django 3.2.7 on 2021-10-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0015_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Out Of Stock'), (1, 'Active')], default=0),
        ),
    ]
